"""Update SocialPlatform enum to prioritize OAuth platforms

Revision ID: 86da145b283c
Revises: eb2af4e912e5
Create Date: 2025-07-18 15:55:56.378644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86da145b283c'
down_revision = 'eb2af4e912e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
