"""Add platform_username and platform_avatar_url to social_connections and create oauth_states table

Revision ID: f867c4bcc8a8
Revises: 86da145b283c
Create Date: 2025-07-18 16:45:53.095335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867c4bcc8a8'
down_revision = '86da145b283c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Import the existing SocialPlatform enum type
    from sqlalchemy.dialects.postgresql import ENUM
    socialplatform_enum = ENUM('GOOGLE', 'FACEBOOK', 'TIKTOK', 'TWITTER', 'INSTAGRAM', 'LINKEDIN', 'YOUTUBE', name='socialplatform', create_type=False)
    
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', socialplatform_enum, nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_id'), 'oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.add_column('social_connections', sa.Column('platform_username', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('platform_avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'platform_avatar_url')
    op.drop_column('social_connections', 'platform_username')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
